/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
    package ev3.jpanel;
    import ev3.clases.Detallefact;
    import ev3.clases.Datos;
    import listas.Lista;
    import bd.Conect;
import javax.swing.JOptionPane;

/**
 *
 * @author v-tokyo
 */
public class Detallefactura extends javax.swing.JFrame {
    Datos datosCliente;
    /**
     * Creates new form Detallefactura
     */
    private Detallefact factura;
    public Detallefactura(Datos datosCliente1) {
        this.datosCliente=datosCliente1;
        initComponents();
        this.setLocationRelativeTo(null);
    }
    public Detallefactura(){
        initComponents();
         this.setLocationRelativeTo(null);
    }
    //validadores son todos booleanos van con un if y else 
        boolean codigoval=false;
        boolean valorval=false;
        boolean ivaval=false;
    //objeto vacio
        Detallefact fact1=new Detallefact();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCodigo = new javax.swing.JLabel();
        jTextFieldCodigo = new javax.swing.JTextField();
        jLabelDescripcion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabelCantidad = new javax.swing.JLabel();
        jTextFieldCantidad = new javax.swing.JTextField();
        jLabelPrecio = new javax.swing.JLabel();
        jTextFieldCodigo1 = new javax.swing.JTextField();
        jTextFieldPrecio = new javax.swing.JTextField();
        jLabelDescuento = new javax.swing.JLabel();
        jLabelMontoneto1 = new javax.swing.JLabel();
        jTextFieldDescuento = new javax.swing.JTextField();
        jLabelValor = new javax.swing.JLabel();
        jTextFieldValor = new javax.swing.JTextField();
        jLabelMontoneto = new javax.swing.JLabel();
        jTextFieldMontoneto = new javax.swing.JTextField();
        jLabeliva = new javax.swing.JLabel();
        jTextFieldiva = new javax.swing.JTextField();
        jLabelimpad = new javax.swing.JLabel();
        jTextFieldImpad = new javax.swing.JTextField();
        jLabelTotal = new javax.swing.JLabel();
        jTextFieldTotal = new javax.swing.JTextField();
        jLabelTitulo = new javax.swing.JLabel();
        jButtonVolver = new javax.swing.JButton();
        jButtonGuardar = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelCodigo.setForeground(new java.awt.Color(204, 204, 204));
        jLabelCodigo.setText("Codigo:");
        getContentPane().add(jLabelCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, -1));

        jTextFieldCodigo.setBackground(new java.awt.Color(255, 255, 204));
        jTextFieldCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodigoActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 80, 20));

        jLabelDescripcion.setForeground(new java.awt.Color(204, 204, 204));
        jLabelDescripcion.setText("Descripcion:");
        getContentPane().add(jLabelDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, -1, -1));

        jTextArea1.setBackground(new java.awt.Color(255, 255, 204));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, 290, 110));

        jLabelCantidad.setForeground(new java.awt.Color(204, 204, 204));
        jLabelCantidad.setText("Cantidad:");
        getContentPane().add(jLabelCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, -1));

        jTextFieldCantidad.setBackground(new java.awt.Color(255, 255, 204));
        jTextFieldCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCantidadActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 80, 20));

        jLabelPrecio.setForeground(new java.awt.Color(204, 204, 204));
        jLabelPrecio.setText("Precio:");
        getContentPane().add(jLabelPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, -1, -1));

        jTextFieldCodigo1.setBackground(new java.awt.Color(255, 255, 204));
        jTextFieldCodigo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodigo1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldCodigo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 260, 80, 20));

        jTextFieldPrecio.setBackground(new java.awt.Color(255, 255, 204));
        jTextFieldPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPrecioActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, 70, 20));

        jLabelDescuento.setForeground(new java.awt.Color(204, 204, 204));
        jLabelDescuento.setText("Descuento:");
        getContentPane().add(jLabelDescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, -1, -1));

        jLabelMontoneto1.setForeground(new java.awt.Color(204, 204, 204));
        jLabelMontoneto1.setText("forma de pago");
        getContentPane().add(jLabelMontoneto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, -1, -1));

        jTextFieldDescuento.setBackground(new java.awt.Color(255, 255, 204));
        jTextFieldDescuento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDescuentoActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldDescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, 70, 20));

        jLabelValor.setForeground(new java.awt.Color(204, 204, 204));
        jLabelValor.setText("Valor:");
        getContentPane().add(jLabelValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, -1, -1));

        jTextFieldValor.setBackground(new java.awt.Color(255, 255, 204));
        jTextFieldValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldValorActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 80, 20));

        jLabelMontoneto.setForeground(new java.awt.Color(204, 204, 204));
        jLabelMontoneto.setText("Monto neto:");
        getContentPane().add(jLabelMontoneto, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, -1, -1));

        jTextFieldMontoneto.setBackground(new java.awt.Color(255, 255, 204));
        jTextFieldMontoneto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMontonetoActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldMontoneto, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, 70, 20));

        jLabeliva.setForeground(new java.awt.Color(204, 204, 204));
        jLabeliva.setText("Iva:");
        getContentPane().add(jLabeliva, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, -1, -1));

        jTextFieldiva.setBackground(new java.awt.Color(255, 255, 204));
        jTextFieldiva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldivaActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldiva, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 80, 20));

        jLabelimpad.setForeground(new java.awt.Color(204, 204, 204));
        jLabelimpad.setText("Impuesto adicional:");
        getContentPane().add(jLabelimpad, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, -1, -1));

        jTextFieldImpad.setBackground(new java.awt.Color(255, 255, 204));
        jTextFieldImpad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldImpadActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldImpad, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, 70, 20));

        jLabelTotal.setForeground(new java.awt.Color(204, 204, 204));
        jLabelTotal.setText("Total:");
        getContentPane().add(jLabelTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, -1, -1));

        jTextFieldTotal.setBackground(new java.awt.Color(255, 255, 204));
        jTextFieldTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTotalActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 70, 20));

        jLabelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(204, 204, 204));
        jLabelTitulo.setText("Detalle Factura");
        getContentPane().add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, -1, -1));

        jButtonVolver.setBackground(new java.awt.Color(204, 204, 204));
        jButtonVolver.setText("Volver");
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 460, -1, -1));

        jButtonGuardar.setBackground(new java.awt.Color(204, 204, 204));
        jButtonGuardar.setText("Guardar");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 460, -1, -1));

        jButtonSalir.setBackground(new java.awt.Color(204, 204, 204));
        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 460, -1, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pago-facturas-planificacion-presupuesto-adquirir-riqueza-generada-ia.jpg"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 519));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodigoActionPerformed
        // TODO add your handling code here:
        String code = jTextFieldCodigo.getText();
        fact1.setCodigo(code);
        try {
        int codigo = Integer.parseInt(code);
        if (codigo > 1) {
            fact1.setCodigo(code);
        } else {
            JOptionPane.showMessageDialog(this, "El código debe ser mayor a 1", "Error", JOptionPane.ERROR_MESSAGE);
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Ingrese un número válido para el código", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_jTextFieldCodigoActionPerformed

    private void jTextFieldCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCantidadActionPerformed
        // TODO add your handling code here:
        String cantidad=jTextFieldCantidad.getText();
            try {
        int cantidadValue = Integer.parseInt(cantidad);
        if (cantidadValue > 1) {
            fact1.setCantidad(cantidad);
        } else {
            JOptionPane.showMessageDialog(this, "La cantidad debe ser mayor a 1", "Error", JOptionPane.ERROR_MESSAGE);
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Ingrese un número válido para la cantidad", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_jTextFieldCantidadActionPerformed

    private void jTextFieldValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldValorActionPerformed
        // TODO add your handling code here:
        String valor =jTextFieldValor.getText();
        fact1.setValor(valor);
    }//GEN-LAST:event_jTextFieldValorActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        // TODO add your handling code here:
        super.dispose();
        new Menuprincipal().setVisible(false);
    }//GEN-LAST:event_jButtonVolverActionPerformed

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        // TODO add your handling code here: where crear el objeto en este
        Detallefact fact1=new Detallefact();
        fact1.setCodigo(jTextFieldCodigo.getText());
        fact1.setCantidad(jTextFieldCantidad.getText());
        fact1.setValor(jTextFieldValor.getText());
        fact1.setIva(Integer.parseInt(jTextFieldiva.getText()));
        fact1.setPrecio(jTextFieldPrecio.getText());
        fact1.setDescuento(jTextFieldDescuento.getText());
            fact1.setMontonet(Integer.parseInt(jTextFieldMontoneto.getText()));
        fact1.setImpad(Integer.parseInt(jTextFieldImpad.getText()));
        fact1.setTotal(Integer.parseInt(jTextFieldTotal.getText()));
        fact1.setFormapago(jTextFieldCodigo1.getText());
        
        Lista.agregarfa(fact1);
        bd.Conect.insertarDetalleFactura(
        jTextFieldCodigo.getText(),
        Integer.parseInt(jTextFieldCantidad.getText()),
        Integer.parseInt(jTextFieldDescuento.getText()), // Corregido descuento
        Integer.parseInt(jTextFieldValor.getText()),
        jTextFieldPrecio.getText(),
        Integer.parseInt(jTextFieldMontoneto.getText()),
        Integer.parseInt(jTextFieldiva.getText()),
        Integer.parseInt(jTextFieldImpad.getText()),
        Integer.parseInt(jTextFieldTotal.getText())
);
       //bd.Conect.insertarDetalleFactura(codigoProducto, WIDTH, HEIGHT, ERROR, formaDePago, SOMEBITS, WIDTH, HIDE_ON_CLOSE, NORMAL);
        JOptionPane.showMessageDialog(null,"datos de factura guardados");
        
        
        
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jTextFieldivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldivaActionPerformed
        // TODO add your handling code here:
        int iva = Integer.parseInt(jTextFieldiva.getText());
        fact1.setIva(iva);
        
    }//GEN-LAST:event_jTextFieldivaActionPerformed

    private void jTextFieldPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPrecioActionPerformed
        // TODO add your handling code here:
        String precio=jTextFieldPrecio.getText();
        fact1.setPrecio(precio);
    }//GEN-LAST:event_jTextFieldPrecioActionPerformed

    private void jTextFieldDescuentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDescuentoActionPerformed
        // TODO add your handling code here:
        String descuento=jTextFieldDescuento.getText();
        fact1.setDescuento(descuento);
    }//GEN-LAST:event_jTextFieldDescuentoActionPerformed

    private void jTextFieldMontonetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMontonetoActionPerformed
        // TODO add your handling code here:
        int montonet = Integer.parseInt(jTextFieldMontoneto.getText());
        fact1.setMontonet(montonet);
    }//GEN-LAST:event_jTextFieldMontonetoActionPerformed

    private void jTextFieldImpadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldImpadActionPerformed
        // TODO add your handling code here: impad= impuesto adicional 
        int impad = Integer.parseInt(jTextFieldImpad.getText());
        fact1.setImpad(impad);
    }//GEN-LAST:event_jTextFieldImpadActionPerformed

    private void jTextFieldTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTotalActionPerformed
        // TODO add your handling code here:
        int total=Integer.parseInt(jTextFieldTotal.getText());
        fact1.setTotal(total);
    }//GEN-LAST:event_jTextFieldTotalActionPerformed

    private void jTextFieldCodigo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodigo1ActionPerformed
        // TODO add your handling code here:
        String formpag=jTextFieldCodigo1.getText();
        fact1.setFormapago(formpag);
    }//GEN-LAST:event_jTextFieldCodigo1ActionPerformed
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JLabel jLabelCantidad;
    private javax.swing.JLabel jLabelCodigo;
    private javax.swing.JLabel jLabelDescripcion;
    private javax.swing.JLabel jLabelDescuento;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelMontoneto;
    private javax.swing.JLabel jLabelMontoneto1;
    private javax.swing.JLabel jLabelPrecio;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JLabel jLabelValor;
    private javax.swing.JLabel jLabelimpad;
    private javax.swing.JLabel jLabeliva;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextFieldCantidad;
    private javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JTextField jTextFieldCodigo1;
    private javax.swing.JTextField jTextFieldDescuento;
    private javax.swing.JTextField jTextFieldImpad;
    private javax.swing.JTextField jTextFieldMontoneto;
    private javax.swing.JTextField jTextFieldPrecio;
    private javax.swing.JTextField jTextFieldTotal;
    private javax.swing.JTextField jTextFieldValor;
    private javax.swing.JTextField jTextFieldiva;
    // End of variables declaration//GEN-END:variables
}
