package ev3.jpanel;
import ev3.clases.Datos;
import javax.swing.JOptionPane;
import ev3.clases.Detallefact;
import java.util.ArrayList;
import ev3.jpanel.Detallefactura;
import bd.Conect;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *  ARREGLAR los validadores la cage "acer cada booleano por cada validacion" 
 * @author v-tokyo
 */
public class Ingresarfactura extends javax.swing.JFrame {

    /**
     * Creates new form Ingresarfactura
     */
    private Datos dat1;
    public Ingresarfactura() {
        initComponents();
        this.setLocationRelativeTo(null);
        Datos dat1=new Datos();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
            //validadores
            boolean nombreValido = false;
            boolean rutValido = false;
            boolean direcVal = false;
            boolean fechaVal = false;
            boolean tipoComVal = false;
            boolean giroVal = false;
    private ArrayList<String> listaDetalles = new ArrayList<>();
    private ArrayList<Datos> listaDatos = new ArrayList<>();
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelIngreseNF = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        TextfieldNombre = new javax.swing.JTextField();
        jLabelRut = new javax.swing.JLabel();
        jLabelGiro = new javax.swing.JLabel();
        jTextFieldGiro = new javax.swing.JTextField();
        jLabelDirec = new javax.swing.JLabel();
        jTextFieldDirec = new javax.swing.JTextField();
        jLabelComuna = new javax.swing.JLabel();
        jTextFieldComuna = new javax.swing.JTextField();
        jLabelCiudad = new javax.swing.JLabel();
        jTextFieldCiudad = new javax.swing.JTextField();
        jLabelContacto = new javax.swing.JLabel();
        jTextFieldContacto = new javax.swing.JTextField();
        jLabelFechaE = new javax.swing.JLabel();
        jTextFieldFechaE = new javax.swing.JTextField();
        jLabelTipoCom = new javax.swing.JLabel();
        jTextFieldTipoCom = new javax.swing.JTextField();
        jTextFieldRut = new javax.swing.JTextField();
        jButtonDetalleF = new javax.swing.JButton();
        jButtonVolverAlMenu = new javax.swing.JButton();
        jButtonGuardarDatosCliente = new javax.swing.JButton();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 204, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setForeground(new java.awt.Color(255, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelIngreseNF.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabelIngreseNF.setText("Ingrese Nueva Factura");
        jPanel1.add(jLabelIngreseNF, new org.netbeans.lib.awtextra.AbsoluteConstraints(2462, 109, -1, -1));

        jLabelNombre.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        jLabelNombre.setForeground(new java.awt.Color(204, 204, 204));
        jLabelNombre.setText("Nombre Cliente:");
        jPanel1.add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, -1));

        TextfieldNombre.setBackground(new java.awt.Color(255, 255, 204));
        TextfieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextfieldNombreActionPerformed(evt);
            }
        });
        jPanel1.add(TextfieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 120, -1));

        jLabelRut.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        jLabelRut.setForeground(new java.awt.Color(204, 204, 204));
        jLabelRut.setText("Rut Cliente:");
        jPanel1.add(jLabelRut, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, -1, -1));

        jLabelGiro.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        jLabelGiro.setForeground(new java.awt.Color(204, 204, 204));
        jLabelGiro.setText("Giro:");
        jPanel1.add(jLabelGiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, -1, -1));

        jTextFieldGiro.setBackground(new java.awt.Color(255, 255, 204));
        jTextFieldGiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldGiroActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldGiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 132, 120, 20));

        jLabelDirec.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        jLabelDirec.setForeground(new java.awt.Color(204, 204, 204));
        jLabelDirec.setText("Direccion:");
        jPanel1.add(jLabelDirec, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, -1, -1));

        jTextFieldDirec.setBackground(new java.awt.Color(255, 255, 204));
        jTextFieldDirec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDirecActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldDirec, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 132, 120, -1));

        jLabelComuna.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        jLabelComuna.setForeground(new java.awt.Color(204, 204, 204));
        jLabelComuna.setText("Comuna:");
        jPanel1.add(jLabelComuna, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, -1, -1));

        jTextFieldComuna.setBackground(new java.awt.Color(255, 255, 204));
        jTextFieldComuna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldComunaActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldComuna, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 232, 120, 20));

        jLabelCiudad.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        jLabelCiudad.setForeground(new java.awt.Color(204, 204, 204));
        jLabelCiudad.setText("Ciudad:");
        jPanel1.add(jLabelCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, -1, -1));

        jTextFieldCiudad.setBackground(new java.awt.Color(255, 255, 204));
        jTextFieldCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCiudadActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, 120, -1));

        jLabelContacto.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        jLabelContacto.setForeground(new java.awt.Color(204, 204, 204));
        jLabelContacto.setText("Contacto:");
        jPanel1.add(jLabelContacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, -1, -1));

        jTextFieldContacto.setBackground(new java.awt.Color(255, 255, 204));
        jTextFieldContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldContactoActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldContacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 182, 120, 20));

        jLabelFechaE.setForeground(new java.awt.Color(204, 204, 204));
        jLabelFechaE.setText("Fecha Emision:");
        jPanel1.add(jLabelFechaE, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, -1, -1));

        jTextFieldFechaE.setBackground(new java.awt.Color(255, 255, 204));
        jTextFieldFechaE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFechaEActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldFechaE, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 232, 120, 20));

        jLabelTipoCom.setForeground(new java.awt.Color(204, 204, 204));
        jLabelTipoCom.setText("Tipo de compra:");
        jPanel1.add(jLabelTipoCom, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, -1, -1));

        jTextFieldTipoCom.setBackground(new java.awt.Color(255, 255, 204));
        jTextFieldTipoCom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTipoComActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldTipoCom, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 120, 20));

        jTextFieldRut.setBackground(new java.awt.Color(255, 255, 204));
        jTextFieldRut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRutActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldRut, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, 120, 20));

        jButtonDetalleF.setBackground(new java.awt.Color(204, 204, 204));
        jButtonDetalleF.setText("Detalle Factura");
        jButtonDetalleF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDetalleFActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonDetalleF, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 390, -1, -1));

        jButtonVolverAlMenu.setBackground(new java.awt.Color(204, 204, 204));
        jButtonVolverAlMenu.setText("Menu");
        jButtonVolverAlMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverAlMenuActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonVolverAlMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 110, -1));

        jButtonGuardarDatosCliente.setBackground(new java.awt.Color(204, 204, 204));
        jButtonGuardarDatosCliente.setText("Guardar datos");
        jButtonGuardarDatosCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarDatosClienteActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonGuardarDatosCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 390, -1, -1));

        jLabelTitulo.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(204, 204, 204));
        jLabelTitulo.setText("Datos Cliente");
        jPanel1.add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, -1, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pago-facturas-planificacion-presupuesto-adquirir-riqueza-generada-ia.jpg"))); // NOI18N
        jPanel1.add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 450));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents
        
    private void TextfieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextfieldNombreActionPerformed
        // TODO add your handling code here: nombre
        String nombre = TextfieldNombre.getText();
        dat1.setNombre(TextfieldNombre.getText());

        for (int i = 0; i < 3; i++) {
            nombre = JOptionPane.showInputDialog("Ingrese el nombre: ");

            if (nombre != null && !nombre.isEmpty()) {
                nombreValido = true;
                listaDetalles.add(nombre);
            } else {
                JOptionPane.showMessageDialog(null, "El nombre no puede estar vacío. Inténtelo de nuevo.");
            }
        }

    }//GEN-LAST:event_TextfieldNombreActionPerformed

    private void jTextFieldRutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRutActionPerformed
        // TODO add your handling code here: rut
        String direccion = jTextFieldDirec.getText();
        dat1.setDireccion(jTextFieldDirec.getText());

        if (direccion != null && !direccion.isEmpty()) {
            direcVal = true;
            listaDetalles.add(direccion);
        } else {
            JOptionPane.showMessageDialog(null, "La dirección no puede estar vacía. Inténtelo de nuevo.");
        }
            
    }//GEN-LAST:event_jTextFieldRutActionPerformed

    private void jTextFieldDirecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDirecActionPerformed
        // TODO add your handling code here:
        String direccion = jTextFieldDirec.getText();
        dat1.setDireccion(jTextFieldDirec.getText());

        if (direccion != null && !direccion.isEmpty()) {
            direcVal = true;
            listaDetalles.add(direccion);
        } else {
            JOptionPane.showMessageDialog(null, "La dirección no puede estar vacía. Inténtelo de nuevo.");
        }
    }//GEN-LAST:event_jTextFieldDirecActionPerformed

    private void jTextFieldFechaEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFechaEActionPerformed
        // TODO add your handling code here: fecha de emision revisar si se puede pasar a date o local date 
        String tipoCompra = jTextFieldTipoCom.getText();
        if (tipoCompra != null && !tipoCompra.isEmpty()) {
            tipoComVal = true;
            listaDetalles.add(tipoCompra);
        } else {
            JOptionPane.showMessageDialog(null, "Tipo de compra no válido. Inténtelo de nuevo.");
    }
        
    }//GEN-LAST:event_jTextFieldFechaEActionPerformed

    private void jTextFieldTipoComActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTipoComActionPerformed
        // TODO add your handling code here: tipo de compra
        String tipoCompra = jTextFieldTipoCom.getText();

        if (tipoCompra != null && !tipoCompra.isEmpty()) {
            tipoComVal = true;
            listaDetalles.add(tipoCompra);
    }   else {
            JOptionPane.showMessageDialog(null, "Tipo de compra no válido. Inténtelo de nuevo.");
    }
            
    }//GEN-LAST:event_jTextFieldTipoComActionPerformed

    private void jButtonVolverAlMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverAlMenuActionPerformed
        // TODO add your handling code here:
            super.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_jButtonVolverAlMenuActionPerformed

    private void jButtonDetalleFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDetalleFActionPerformed
        // TODO add your handling code here: crear el objeto pero no deja   
            Detallefactura detalleFrame = new Detallefactura(dat1);
            detalleFrame.setVisible(true);
            this.dispose();
      
       
    }//GEN-LAST:event_jButtonDetalleFActionPerformed

    private void jButtonGuardarDatosClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarDatosClienteActionPerformed
        // TODO add your handling code here:
            Datos dat1=new Datos();
            dat1.setNombre(TextfieldNombre.getText());
            dat1.setRut(Integer.parseInt(jTextFieldRut.getText()));
            dat1.setGiro(jTextFieldGiro.getText());
            dat1.setDireccion(jTextFieldDirec.getText());
            dat1.setComuna(jTextFieldComuna.getText());
            dat1.setCiudad(jTextFieldCiudad.getText());
            dat1.setContacto(jTextFieldContacto.getText());
            dat1.setFechaem(jTextFieldFechaE.getText());
            dat1.setTipcompra(jTextFieldTipoCom.getText());
            JOptionPane.showMessageDialog(null,"datos guardados");
            listaDatos.add(dat1);
            bd.Conect.insertardatosp(jTextFieldRut.getText(), TextfieldNombre.getText(), jTextFieldGiro.getText(), jTextFieldDirec.getText(), jTextFieldComuna.getText(), jTextFieldCiudad.getText(), jTextFieldContacto.getText(), jTextFieldFechaE.getText(), jTextFieldTipoCom.getText());
            jButtonGuardarDatosCliente.addActionListener(new java.awt.event.ActionListener() {
    @Override
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonGuardarDatosClienteActionPerformed(evt);
    }
});

    }//GEN-LAST:event_jButtonGuardarDatosClienteActionPerformed

    private void jTextFieldGiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldGiroActionPerformed
        // TODO add your handling code here:
        String giro = jTextFieldGiro.getText();
        if (giro != null && !giro.isEmpty()) {
            giroVal = true;
            listaDetalles.add(giro);
    }   else {
            JOptionPane.showMessageDialog(null, "Giro no válido. Inténtelo de nuevo.");
    }
        
    }//GEN-LAST:event_jTextFieldGiroActionPerformed

    private void jTextFieldComunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldComunaActionPerformed
        // TODO add your handling code here: comuna
        String comuna = jTextFieldComuna.getText();

        if (comuna != null && !comuna.isEmpty()) {
            nombreValido = true;
            listaDetalles.add(comuna);
    }   else {
            JOptionPane.showMessageDialog(null, "Comuna no válida. Inténtelo de nuevo.");
    }
    }//GEN-LAST:event_jTextFieldComunaActionPerformed

    private void jTextFieldCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCiudadActionPerformed
        // TODO add your handling code here:
        String ciudad = jTextFieldCiudad.getText();

        if (ciudad != null && !ciudad.isEmpty()) {
            nombreValido = true;
            listaDetalles.add(ciudad);
    }   else {
            JOptionPane.showMessageDialog(null, "Ciudad no válida. Inténtelo de nuevo.");
    }
    }//GEN-LAST:event_jTextFieldCiudadActionPerformed

    private void jTextFieldContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldContactoActionPerformed
        // TODO add your handling code here:
        String contacto = jTextFieldContacto.getText();

        if (contacto != null && !contacto.isEmpty()) {
            nombreValido = true;
            listaDetalles.add(contacto);
    }   else {
            JOptionPane.showMessageDialog(null, "Contacto no válido. Inténtelo de nuevo.");
    }
    }//GEN-LAST:event_jTextFieldContactoActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TextfieldNombre;
    private javax.swing.JButton jButtonDetalleF;
    private javax.swing.JButton jButtonGuardarDatosCliente;
    private javax.swing.JButton jButtonVolverAlMenu;
    private javax.swing.JLabel jLabelCiudad;
    private javax.swing.JLabel jLabelComuna;
    private javax.swing.JLabel jLabelContacto;
    private javax.swing.JLabel jLabelDirec;
    private javax.swing.JLabel jLabelFechaE;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelGiro;
    private javax.swing.JLabel jLabelIngreseNF;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelRut;
    private javax.swing.JLabel jLabelTipoCom;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldCiudad;
    private javax.swing.JTextField jTextFieldComuna;
    private javax.swing.JTextField jTextFieldContacto;
    private javax.swing.JTextField jTextFieldDirec;
    private javax.swing.JTextField jTextFieldFechaE;
    private javax.swing.JTextField jTextFieldGiro;
    private javax.swing.JTextField jTextFieldRut;
    private javax.swing.JTextField jTextFieldTipoCom;
    // End of variables declaration//GEN-END:variables






}
