/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ev3.jpanel;

import bd.Conect;
import static bd.Conect.obtenerConexion;
import ev3.clases.Datos;
import ev3.clases.Detallefact;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import listas.Listadatos;
import listas.Lista;

import java.util.ArrayList;
import javax.swing.Box;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;


/**

 * @author v-tokyo
 */
public class Listar extends javax.swing.JFrame {

    private final ArrayList<Datos> listaDatos;
    private final ArrayList<Detallefact> listaDetalles;


    /**
     * Creates new form Listar
     */
    public Listar() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.listaDatos = new ArrayList<>();
        this.listaDetalles = new ArrayList<>();
        //mostrarInformacion(Listadatos.getListaDatos(),"lista datos: ");
        //mostrarInformacion(Lista.getListaDetalles(),"lista detalle factura: ");
        System.out.println("Antes de obtener datos desde BD");
        //ArrayList<Datos> datosDesdeBD = Conect.obtenerDatosDesdeBD();
        mostrarInformacion(Conect.obtenerDatosDesdeBD(), "lista datos :");
        mostrarInformacion(Conect.obtenerDatosfact(),"facturas");
        System.out.println("Después de obtener datos desde BD");
        System.out.println(listaDatos);
        System.out.println(Conect.obtenerDatosDesdeBD());
        System.out.println(Lista.getListaDetalles());
    
    }
    private void mostrarInformacion(ArrayList<?> lista, String titulo) {
    System.out.println("Mostrando información: " + titulo);
    JTextArea textArea = new JTextArea();
    textArea.setLineWrap(true);
    textArea.setWrapStyleWord(true);
    textArea.setEditable(false);
    textArea.append(titulo + "\n\n");
    textArea.setForeground(new java.awt.Color(0, 0, 0));

    for (Object objeto : lista) {
        if (objeto instanceof Datos) {
                Datos datos = (Datos) objeto;
                textArea.append("Nombre: " + datos.getNombre() + "\n");
                textArea.append("RUT: " + datos.getRut() + "\n");
                textArea.append("Giro: " + datos.getGiro() + "\n");
                textArea.append("Dirección: " + datos.getDireccion() + "\n");
                textArea.append("Comuna: " + datos.getComuna() + "\n");
                textArea.append("Ciudad: " + datos.getCiudad() + "\n");
                textArea.append("Contacto: " + datos.getContacto() + "\n");
                textArea.append("Fecha de Emisión: " + datos.getFechaem() + "\n");
                textArea.append("Tipo de Compra: " + datos.getTipcompra() + "\n");
                textArea.append("----------------------------\n");
        } else if (objeto instanceof Detallefact) {
                Detallefact detalle = (Detallefact) objeto;
                textArea.append("Código: " + detalle.getCodigo() + "\n");
                textArea.append("Descripción: " + detalle.getDescripcion() + "\n");
                textArea.append("Cantidad: " + detalle.getCantidad() + "\n");
                textArea.append("Precio: " + detalle.getPrecio() + "\n");
                textArea.append("Descuento: " + detalle.getDescuento() + "\n");  
                textArea.append("Impuesto adicional: " + detalle.getImpad() + "\n");  
                textArea.append("Valor: " + detalle.getValor() + "\n");
                Datos datosAsociados = detalle.getDatosCliente();
                if (datosAsociados != null) {
                    textArea.append("RUT Asociado: " + datosAsociados.getRut() + "\n");
        }
            textArea.append("----------------------------\n");
        }}
            JScrollPane scrollPane = new JScrollPane(textArea);
            jlistado2.add(scrollPane);
            jlistado2.add(Box.createVerticalStrut(10));
            System.out.println("Información mostrada.");
            scrollPane.revalidate();
            scrollPane.repaint();
                


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrolllistado = new javax.swing.JScrollPane();
        jlistado2 = new javax.swing.JPanel();
        jButtonVolver = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlistado2.setLayout(new javax.swing.BoxLayout(jlistado2, javax.swing.BoxLayout.Y_AXIS));
        jScrolllistado.setViewportView(jlistado2);

        getContentPane().add(jScrolllistado, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 990, 460));

        jButtonVolver.setBackground(new java.awt.Color(204, 204, 204));
        jButtonVolver.setText("Volver");
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 530, -1, -1));

        jButtonSalir.setBackground(new java.awt.Color(204, 204, 204));
        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 530, -1, -1));

        jLabelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(204, 204, 204));
        jLabelTitulo.setText("Listado");
        getContentPane().add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, -1, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pago-facturas-planificacion-presupuesto-adquirir-riqueza-generada-ia.jpg"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 577));
        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        // TODO add your handling code here:
        super.dispose();
        new Menuprincipal().setVisible(false);
    }//GEN-LAST:event_jButtonVolverActionPerformed

    public JPanel getJlistado2() {
        return jlistado2;
    }

 

 



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrolllistado;
    private javax.swing.JPanel jlistado2;
    // End of variables declaration//GEN-END:variables

}
