package ev3.jpanel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author v-tokyo
 */
public class Menuprincipal extends javax.swing.JFrame {

    /**
     * Creates new form Menuprincipal
     */
    public Menuprincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btonIngresarF = new javax.swing.JButton();
        btonListarF = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btonEliminarF = new javax.swing.JButton();
        jButtonsalir = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btonIngresarF.setBackground(new java.awt.Color(255, 255, 204));
        btonIngresarF.setText("Ingresar Factura");
        btonIngresarF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btonIngresarFActionPerformed(evt);
            }
        });
        jPanel1.add(btonIngresarF, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 140, -1));

        btonListarF.setBackground(new java.awt.Color(255, 255, 204));
        btonListarF.setText("Listar Factura");
        btonListarF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btonListarFActionPerformed(evt);
            }
        });
        jPanel1.add(btonListarF, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 140, -1));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Sistema  Facturas");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 160, 30));

        btonEliminarF.setBackground(new java.awt.Color(255, 255, 204));
        btonEliminarF.setText("Eliminar Factura");
        btonEliminarF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btonEliminarFActionPerformed(evt);
            }
        });
        jPanel1.add(btonEliminarF, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 140, -1));

        jButtonsalir.setBackground(new java.awt.Color(204, 204, 204));
        jButtonsalir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonsalir.setText("Salir");
        jButtonsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsalirActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, -1, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pago-facturas-planificacion-presupuesto-adquirir-riqueza-generada-ia.jpg"))); // NOI18N
        jPanel1.add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, 0, 400, 400));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btonIngresarFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btonIngresarFActionPerformed
        new Ingresarfactura().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btonIngresarFActionPerformed

    private void jButtonsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButtonsalirActionPerformed

    private void btonListarFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btonListarFActionPerformed
        // TODO add your handling code here:
        new Listar().setVisible(true);
    }//GEN-LAST:event_btonListarFActionPerformed

    private void btonEliminarFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btonEliminarFActionPerformed
        // TODO add your handling code here:
        new Eliminarfactura().setVisible(true);
    }//GEN-LAST:event_btonEliminarFActionPerformed

//

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btonEliminarF;
    private javax.swing.JButton btonIngresarF;
    private javax.swing.JButton btonListarF;
    private javax.swing.JButton jButtonsalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables



}
